version: '3'

services:
  pg:
    image: postgres:latest 
    environment:
      POSTGRES_DB: postgres2
      POSTGRES_USER: name1
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata

volumes:
  db-data:
