version: '3'

services:
  pg:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres2
      POSTGRES_USER: name1
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata

  backend:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=pg
      - DB_USER=name1
      - DB_PASS=pass
      - DB_NAME=postgres2
    depends_on:
      - pg

  vue-app:
    build:
      context: ../frontend
      dockerfile: DockerFile
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  db-data:
